import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/Components/Navigation";
import {Footer} from "@/Components/Footer";
import {ScrollToTop} from "@/Components/TopArrowButton";
import ChatWidget from "@/Components/Widget";


const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Navigation />
        <main>{children}</main>
        <Footer />
        <ScrollToTop />
        <ChatWidget />
      </body>
    </html>
  );
}
